services:
  backend:
    build:
      context: ./message-back-app
      dockerfile: dev.Dockerfile
    volumes:
      - ./message-back-app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://messageOwner:the_password@mongo:27017/message_dev
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: message_dev
    volumes:
      - ./message-back-app/mongo_init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  frontend:
    build:
      context: ./message-frontend-app
      dockerfile: dev.Dockerfile
    volumes:
      - ./message-frontend-app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
